### ISSUE TITLE
Unable to reference HTTP source address from the HTTP source 

### ISSUE THREAD

**Issue by carlapcastro** [BSick7/terraform-provider-sumologic#1]
I'm using Terraform to set up the infrastructure in order to send Cloudwatch logs to Sumologic through lambda. I need to create an HTTP source and reference the HTTP source address in my lambda function. I want to be able to create all of my resources dynamically and not have to bake in the address into my code.

**Comment by BSick7** [comment]
Can you provide some more detail?

**Comment by carlapcastro** [comment]
@BSick7 Sorry about that. I added more detail about what I'm trying to do. Hopefully that makes sense.

**Comment by BSick7** [comment]
~~Do you have repro steps?
What exactly is not working for you?~~

Nevermind, I see what you're asking for.
Let me take a look.

**Comment by BSick7** [comment]
@carlapcastro Added `sumologic_http_source.url`. 
See https://github.com/BSick7/terraform-provider-sumologic/commit/71ab40bbb0065e97fef6953a21cc0496a13dd88e
